CREATE TABLE roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE users (
    users_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

CREATE TABLE course (
    course_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id BIGINT,
    course_name VARCHAR(100) NOT NULL,
    course_description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_course_instructor FOREIGN KEY (instructor_id) REFERENCES users(users_id)
);

CREATE TABLE enrollment (
    enrollment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    enrollment_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    enrolled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_enrollment_user_course UNIQUE (users_id, course_id),
    CONSTRAINT fk_enrollment_user FOREIGN KEY (users_id) REFERENCES users(users_id),
    CONSTRAINT fk_enrollment_course FOREIGN KEY (course_id) REFERENCES course(course_id)
);

CREATE TABLE document (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    document_name VARCHAR(150) NOT NULL,
    document_text TEXT NOT NULL,
    file_url VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_document_course FOREIGN KEY (course_id) REFERENCES course(course_id)
);

CREATE TABLE reflections (
    reflections_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    understood_content TEXT NOT NULL,
    difficult_content TEXT NOT NULL,
    question_content TEXT,
    reflection_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_reflections_user FOREIGN KEY (users_id) REFERENCES users(users_id),
    CONSTRAINT fk_reflections_course FOREIGN KEY (course_id) REFERENCES course(course_id)
);

CREATE INDEX idx_document_course ON document(course_id);
CREATE INDEX idx_reflections_user_course ON reflections(users_id, course_id);

